// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dougenik_core_cpp
Rcpp::ComplexVector dougenik_core_cpp(Rcpp::ComplexVector pts, Rcpp::ComplexVector C, Rcpp::DoubleVector radii, Rcpp::DoubleVector masses, double forceReductionFactor);
RcppExport SEXP _cartogram_dougenik_core_cpp(SEXP ptsSEXP, SEXP CSEXP, SEXP radiiSEXP, SEXP massesSEXP, SEXP forceReductionFactorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::ComplexVector >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< Rcpp::ComplexVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< Rcpp::DoubleVector >::type radii(radiiSEXP);
    Rcpp::traits::input_parameter< Rcpp::DoubleVector >::type masses(massesSEXP);
    Rcpp::traits::input_parameter< double >::type forceReductionFactor(forceReductionFactorSEXP);
    rcpp_result_gen = Rcpp::wrap(dougenik_core_cpp(pts, C, radii, masses, forceReductionFactor));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cartogram_dougenik_core_cpp", (DL_FUNC) &_cartogram_dougenik_core_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_cartogram(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
