# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dougenik_core_cpp <- function(pts, C, radii, masses, forceReductionFactor) {
    .Call('_cartogram_dougenik_core_cpp', PACKAGE = 'cartogram', pts, C, radii, masses, forceReductionFactor)
}

